### ISSUE TITLE
OpenEXR Error while running the train files.

### ISSUE THREAD

**Issue by sneha-gathani** [joeylitalien/noise2noise-pytorch#5]
Traceback (most recent call last):
  File "train.py", line 7, in <module>
    from datasets import load_dataset
  File "/Users/snehagathani/Desktop/noise/src/datasets.py", line 9, in <module>
    from utils import load_hdr_as_tensor
  File "/Users/snehagathani/Desktop/noise/src/utils.py", line 12, in <module>
    import OpenEXR
ImportError: dlopen(/anaconda3/lib/python3.6/site-packages/OpenEXR.cpython-36m-darwin.so, 2): Symbol not found: __ZN7Imf_2_314TypedAttributeISsE13readValueFromERNS_7IStreamEii
  Referenced from: /anaconda3/lib/python3.6/site-packages/OpenEXR.cpython-36m-darwin.so
  Expected in: flat namespace
 in /anaconda3/lib/python3.6/site-packages/OpenEXR.cpython-36m-darwin.so

This error comes for all the training files.

**Comment by joeylitalien** [comment]
Hi Sneha,

The OpenEXR module is only used for the experimental Monte Carlo denoising, you can safely comment the part of the code that deals with it. Or you can try re-installing OpenEXR. A quick google at your problem revealed that you are not the first with this issue but I am unsure how to solve it on Windows. In any case, it is not essential to the default N2N code.

Cheers,
J.
